spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
         native:
         #search-locations: "classpath:/config"
         #search-locations: "file:///Users//Documents//config"
         git:
           uri: "https://github.com/MAKAINI/eazybyte.git"
           default-label: main
           timeout: 5
           clone-on-start: true
           force-full: true

